POST http://localhost:3001/users/new
Content-Type: application/json

{
	"username" : "jam@gmail.com",
	"password" : "jam",
    "name" : "jam",
    "streak" : 0,
	"score" : 0
}

###

GET http://localhost:3001/users

###


GET http://localhost:3001/users/64272c6842a15c79211e2588

###

POST http://localhost:3001/login
Content-Type: application/json

{
	"username" : "jamesTest",
	"password" : "12345"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
	"username" : null,
	"password" : null
}


###

DELETE http://localhost:3001/users/delete/64272a886a5b8677ac687f1b

###

PUT http://localhost:3001/users/edit/64272c6842a15c79211e2588
Content-Type: application/json

{
	"username" : "newDummy",
	"password" : "69",
    "name" : "evenNewerName"
} 

###

PUT http://localhost:3001/users/updateScore/642730d34ba175fb11cabebd
Content-Type: application/json

{
	"incrementScore" : 69
}

###

PUT http://localhost:3001/users/edit/641f7a93de8ccb7bb3452f09
Content-Type: application/json

{
	"username" : "newDummy",
	"password" : "69",
    "name" : "evenNewerName"
} 

###

POST http://localhost:3001/questions/new
Content-Type: application/json

{
"type": "MCQ",
"question": "Sn2 reactions result in an inversion of stereochemistry, meaning that R will switch to S and vice versa.",
"options": ["The leaving group leaving and forming a carbocation.", "A backside attack which results in the leaving group leaving.", "Deprotonation of a beta carbon.", "Carbocation relocation."],
"correct_option": "A backside attack which results in the leaving group leaving."
}

###
POST http://localhost:3001/questions/new
Content-Type: application/json

{
"type": "Match",
"options": {
	"left": ["DMSO", "Carboxylic Acid", "Methane"],
	"right": ["Polar aprotic", "Polar protic", "Nonpolar aprotic"]
},
"correct_option": {
	"DMSO": "Polar aprotic",
	"Carboxylic Acid": "Polar protic",
	"Methane": "Nonpolar aprotic"
}
}

###

GET http://localhost:3001/questions

###

GET http://localhost:3001/questions/6424ef2f1f239e997825dbfc

###

DELETE http://localhost:3001/questions/delete/6424f0565f8c0c6302707014

###

PUT http://localhost:3001/questions/edit/6424ef2f1f239e997825dbfc
Content-Type: application/json

{
"type": "multiple_choice",
"question": "What is the capital of France?",
"options": ["Ooga", "Booga"],
"correct_option": "Ooga"
}

###
# Updates all questions in the database to have unit 1
PUT http://localhost:3001/questions/addUnit
Content-Type: application/json

{
	"unit": 1
}

###
# Updates all questions in the database to have lesson 1
PUT http://localhost:3001/questions/addLesson
Content-Type: application/json

{
	"lesson": 1
}

###

POST http://localhost:3001/units/new
Content-Type: application/json

{
	"title": "Unit 1: Mechanisms",
	"lessons": [
		{
			"name": "Lesson 1: What are Sn2 Reactions?",
			"stage": 1
		},
		{
			"name": "Lesson 2: What changes the speed of Sn2 Reactions?",
			"stage": 2
		}
	],
	"stage": 1
}


###

GET http://localhost:3001/units

###

DELETE http://localhost:3001/units/delete/642a68dd7c2cac5e2f5ffae7
