POST http://localhost:3001/users/new
Content-Type: application/json

{
	"username" : "jam@gmail.com",
	"password" : "jam",
    "name" : "jam",
    "streak" : 0,
	"score" : 0
}

###

GET http://localhost:3001/users

###


GET http://localhost:3001/users/64272c6842a15c79211e2588

###

POST http://localhost:3001/login
Content-Type: application/json

{
	"username" : "jamesTest",
	"password" : "12345"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
	"username" : null,
	"password" : null
}


###

DELETE http://localhost:3001/users/delete/64272a886a5b8677ac687f1b

###

PUT http://localhost:3001/users/edit/64272c6842a15c79211e2588
Content-Type: application/json

{
	"username" : "newDummy",
	"password" : "69",
    "name" : "evenNewerName"
} 

###

PUT http://localhost:3001/users/updateScore/642730d34ba175fb11cabebd
Content-Type: application/json

{
	"incrementScore" : 69
}

###

PUT http://localhost:3001/users/edit/641f7a93de8ccb7bb3452f09
Content-Type: application/json

{
	"username" : "newDummy",
	"password" : "69",
    "name" : "evenNewerName"
} 

###

POST http://localhost:3001/questions/new
Content-Type: application/json

{
"type": "MCQ",
"question": "Which of the following is the reason for the activation energy barrier for Sn2 reactions?",
"options": ["You have to break bonds during the transition state.", "You have to orient molecules during the transition state.", "You have to form bonds during the transition state.", "Both the first two options."],
"correct_option": "Both the first two options.",
"unit": 1,
"lesson": 1,
"explanation": "The activation energy comes from the need to break bonds and also because molecules need to orient themselves so that a nucleophile can attack a carbon 180 degrees from the halogen (backside attack). Molecules naturally go towards more entropy. When the molecules orient, there is less entropy, meaning energy is required."
}

###

POST http://localhost:3001/questions/new
Content-Type: application/json

{
"type": "TF",
"question": "Sn2 reactions result in an inversion of stereochemistry, meaning that R will switch to S and vice versa.",
"correct_option": "False",
"unit": 1,
"lesson": 1,
"explanation": "An inversion of stereochemistry doesn’t necessarily mean a change in absolute configuration because it depends on the molecule getting added (it might be heavier or lighter compared to the other molecules on the tetravalent carbon)."
}

###

POST http://localhost:3001/questions/new
Content-Type: application/json

{
"type": "Match",
"options": {
	"left": ["Ooga"],
	"right": ["Booga"]
},
"correct_option": {
	"Ooga": "Booga"
},
"unit": 2,
"lesson": 1
}

###

POST http://localhost:3001/questions/new
Content-Type: application/json

{
"type": "imgMCQ",
"question": "Predict the product for the following reaction.",
"questionImg": "U1L1Q3QI",
"options": ["U1L1Q3O1", "U1L1Q3O2", "U1L1Q3O3", "U1L1Q3O4"],
"correct_option": "U1L1Q3O1",
"unit": 1,
"lesson": 1,
"explanation": "Cyanide is a good nucleophile, and it will attack the carbon attached to the Br from the back and kick off the Br in the process."
}

###

GET http://localhost:3001/questions

###

GET http://localhost:3001/questions/1/1

###

GET http://localhost:3001/questions/642c9e909ff89f18709b1a3c

###

DELETE http://localhost:3001/questions/delete/642db0dcac40d8715af27d0e

###

PUT http://localhost:3001/questions/edit/642b2a9d635c59db9eec1327
Content-Type: application/json

{
	  "type": "MCQ",
  "unit": 1,
  "lesson": 2,
  "question": "Ooga?",
  "options": [
    "Booga.",
    "Cooga.",
    "Dooga."
  ],
"correct_option": "Booga."
}

###
# Updates all questions in the database to have unit 1
PUT http://localhost:3001/questions/addUnit
Content-Type: application/json

{
	"unit": 1
}

###
# Updates all questions in the database to have lesson 1
PUT http://localhost:3001/questions/addLesson
Content-Type: application/json

{
	"lesson": 1
}

###

POST http://localhost:3001/units/new
Content-Type: application/json

{
	"title": "Unit 1: Mechanisms",
	"lessons": [
		{
			"name": "Lesson 1: What are Sn2 Reactions?",
			"lessonStage": 1,
			"unitStage": 1
		},
		{
			"name": "Lesson 2: What changes the speed of Sn2 Reactions?",
			"lessonStage": 2,
			"unitStage": 1
		}
	],
	"stage": 1
}


###

GET http://localhost:3001/units

###

DELETE http://localhost:3001/units/delete/642a6cc607a167f55d03841e
